apiVersion: batch/v1
kind: CronJob
metadata:
  name: crawler
spec:
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: crawler
            securityContext:
              runAsUser: 1000
              allowPrivilegeEscalation: false
              runAsNonRoot: true
              seccompProfile:
                type: RuntimeDefault
              capabilities:
                drop:
                - "ALL"
